baseurl = "https://a-pyrkin.github.io/"
title = "Alex"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "a-pyrkin"

[params]
    author = "Alexander Pyrkin"
    description = "Alexander Pyrkin personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/a-pyrkin/"
[[params.social]]
    name = "Stack Overflow"
    weight = 2
    url = "https://stackoverflow.com/users/4175583/alexander-pyrkin/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/alexander-pyrkin-1b2694b1/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
